openapi: 3.0.0
info:
  title: Purchase Order API
  description: API for managing purchase orders
  version: 1.0.0
servers:
  - url: http://stockearte-backend:8080
    description: Local server
paths:
  /purchase-orders:
    get:
      summary: Retrieve a filtered list of purchase orders
      description: This endpoint returns a filtered list of purchase orders.
      operationId: getPurchaseOrders
      parameters:
        - name: id
          in: query
          description: Id to get, 0 for all orders
          required: false
          schema:
            type: integer
            example: 10
        - in: query
          name: codigoProducto
          schema:
            type: string
          description: CÃ³digo del producto a filtrar
        - in: query
          name: fechaDesde
          schema:
            type: string
            format: date
          description: Fecha de inicio del rango de fechas
        - in: query
          name: fechaHasta
          schema:
            type: string
            format: date
          description: Fecha de fin del rango de fechas
        - in: query
          name: estado
          schema:
            type: string
          description: Estado de la orden (Pendiente, Procesado, Completado, etc.)
        - in: query
          name: tienda
          schema:
            type: string
          description: ID de la tienda (solo accesible para usuarios de casa central)
      responses:
        '200':
          description: A list of purchase orders
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/PurchaseOrder'
        '500':
          description: Internal server error
  /filters:
    post:
      summary: Create a new filters model
      operationId: createFiltersModel
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/CreateFiltersModelRequest'
      responses:
        '200':
          description: Successful response with the created filter ID
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/CreateFiltersModelResponse'
        '400':
          description: Bad request
    put:
      summary: Update an existing filters model
      operationId: updateFiltersModel
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/UpdateFiltersModelRequest'
      responses:
        '200':
          description: Successful update response
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/UpdateFiltersModelResponse'
        '404':
          description: Filter not found
    delete:
      summary: Delete a filters model by ID
      operationId: deleteFiltersModel
      parameters:
        - name: id
          in: query
          description: ID of the filter to delete
          required: true
          schema:
            type: integer
      responses:
        '200':
          description: Successful deletion response
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/DeleteFiltersModelResponse'
        '404':
          description: Filter not found
components:
  schemas:
    PurchaseOrder:
      type: object
      properties:
        id:
          type: integer
          format: int64
          example: 123456789
        orders:
          type: array
          items:
            $ref: '#/components/schemas/OrderDetail'
        estado:
          type: string
          example: pending
        observaciones:
          type: string
          example: "Customer requested fast delivery."
        orden_despacho:
          type: string
          example: "OD-98765"
        fechaSolicitud:
          type: string
          format: date-time
          example: "2024-10-10T15:30:00Z"
        fechaRecepcion:
          type: string
          format: date-time
          example: "2024-10-12T10:00:00Z"
        idTienda:
          type: integer
          example: 1001
    OrderDetail:
      type: object
      properties:
        codigo:
          type: string
          example: "ABC123"
        color:
          type: string
          example: "Red"
        talle:
          type: string
          example: "M"
        cantidad:
          type: integer
          format: int32
          example: 2
    CreateFiltersModelRequest:
      type: object
      properties:
        productCode:
          type: string
          example: "ABC123"
        filtersName:
          type: string
          example: "New Filter"
        state:
          type: string
          example: "active"
        idTienda:
          type: integer
          example: 1001
        desde:
          type: string
          format: date
          example: "2024-01-01"
        hasta:
          type: string
          format: date
          example: "2024-12-31"
        habilitado:
          type: boolean
          example: true
    CreateFiltersModelResponse:
      type: object
      properties:
        id:
          type: integer
          example: 1
    UpdateFiltersModelRequest:
      type: object
      properties:
        id:
          type: integer
          example: 1
        productCode:
          type: string
          example: "ABC123"
        filtersName:
          type: string
          example: "Updated Filter"
        state:
          type: string
          example: "active"
        idTienda:
          type: integer
          example: 1001
        desde:
          type: string
          format: date
          example: "2024-01-01"
        hasta:
          type: string
          format: date
          example: "2024-12-31"
        habilitado:
          type: boolean
          example: true
    UpdateFiltersModelResponse:
      type: object
      properties:
        success:
          type: boolean
          example: true
    DeleteFiltersModelResponse:
      type: object
      properties:
        success:
          type: boolean
          example: true